name: SpigotSpring
author: CChuYong
website: https://chuyong.kr
version: 0.0.1
main: chuyong.springspigot.SpringSpigotBootstrapper
api-version: 1.17
load: STARTUP
libraries:
  - org.apache.commons:commons-lang3:3.12.0
  - com.github.f4b6a3:ulid-creator:5.2.0
  - mysql:mysql-connector-java:8.0.28
  - com.h2database:h2:1.4.200
  - net.bytebuddy:byte-buddy:1.14.5
