name: Build Project and upload
on:
  push:
    branches: [ 'main' ]
concurrency:
  group: build

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: Build Java Project

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Retrieve the repository
        uses: actions/checkout@v3

      - name: Prepare JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Prepare Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get Version from Gradle
        id: get_version
        run: echo "::set-output name=version::$(./gradlew -q printVersion)"

      - name: Publish Image to Maven
        id: publish-image
        run: ./gradlew publishAll --parallel -Drelease=true

      - name: Release Tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          commit: ${{ github.sha }}
          artifacts: 'build/libs/*.jar'
