name: Build Project and upload
on:
  push:
    branches: [ 'main' ]
    paths:
      - 'src/**'
      - 'build.gradle.kts'

concurrency:
  group: build

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: Build Java Project

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Retrieve the repository
        uses: actions/checkout@v3

      - name: Prepare JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Prepare Gradle
        uses: gradle/gradle-build-action@v2

#      - name: Build Gradle
#        id: build-image
#        run: ./gradlew shadowJar //For Release AutoTag

      - name: Publish Image to Maven
        id: publish-image
        run: ./gradlew publish
